name: Build and Release Converter

on:
  push:
    tags:
      - "release-*"

jobs:
  build:
    name: Build for All Platforms
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"

      - name: Build binary
        working-directory: converter
        run: |
          mkdir -p dist
          output_name="converter-${{ matrix.goos }}-${{ matrix.goarch }}"
          if [ "${{ matrix.goos }}" = "windows" ]; then
            output_name="${output_name}.exe"
          fi
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} \
            go build -o "dist/${output_name}" ./cmd/converter

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ matrix.goos }}-${{ matrix.goarch }}
          path: converter/dist/

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: converter/dist/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: converter/dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
